export interface Country {
  flag: string;
  code: string;
  iso: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  // Africa
  { flag: "🇰🇪", code: "+254", iso: "KE", name: "Kenya" },
  { flag: "🇳🇬", code: "+234", iso: "NG", name: "Nigeria" },
  { flag: "🇿🇦", code: "+27",  iso: "ZA", name: "South Africa" },
  { flag: "🇹🇿", code: "+255", iso: "TZ", name: "Tanzania" },
  { flag: "🇺🇬", code: "+256", iso: "UG", name: "Uganda" },
  { flag: "🇬🇭", code: "+233", iso: "GH", name: "Ghana" },
  { flag: "🇪🇹", code: "+251", iso: "ET", name: "Ethiopia" },
  { flag: "🇷🇼", code: "+250", iso: "RW", name: "Rwanda" },
  { flag: "🇿🇲", code: "+260", iso: "ZM", name: "Zambia" },
  { flag: "🇿🇼", code: "+263", iso: "ZW", name: "Zimbabwe" },
  { flag: "🇧🇼", code: "+267", iso: "BW", name: "Botswana" },
  { flag: "🇲🇼", code: "+265", iso: "MW", name: "Malawi" },
  { flag: "🇲🇿", code: "+258", iso: "MZ", name: "Mozambique" },
  { flag: "🇸🇳", code: "+221", iso: "SN", name: "Senegal" },
  { flag: "🇨🇮", code: "+225", iso: "CI", name: "Côte d'Ivoire" },
  { flag: "🇨🇲", code: "+237", iso: "CM", name: "Cameroon" },
  { flag: "🇦🇴", code: "+244", iso: "AO", name: "Angola" },
  { flag: "🇸🇩", code: "+249", iso: "SD", name: "Sudan" },
  { flag: "🇩🇿", code: "+213", iso: "DZ", name: "Algeria" },
  { flag: "🇪🇬", code: "+20",  iso: "EG", name: "Egypt" },
  { flag: "🇲🇦", code: "+212", iso: "MA", name: "Morocco" },
  { flag: "🇹🇳", code: "+216", iso: "TN", name: "Tunisia" },
  { flag: "🇱🇾", code: "+218", iso: "LY", name: "Libya" },
  { flag: "🇸🇸", code: "+211", iso: "SS", name: "South Sudan" },
  { flag: "🇸🇴", code: "+252", iso: "SO", name: "Somalia" },
  { flag: "🇩🇯", code: "+253", iso: "DJ", name: "Djibouti" },
  { flag: "🇪🇷", code: "+291", iso: "ER", name: "Eritrea" },
  { flag: "🇧🇮", code: "+257", iso: "BI", name: "Burundi" },
  { flag: "🇨🇩", code: "+243", iso: "CD", name: "DR Congo" },
  { flag: "🇨🇬", code: "+242", iso: "CG", name: "Congo" },
  { flag: "🇬🇦", code: "+241", iso: "GA", name: "Gabon" },
  { flag: "🇬🇶", code: "+240", iso: "GQ", name: "Eq. Guinea" },
  { flag: "🇨🇫", code: "+236", iso: "CF", name: "C. African Rep." },
  { flag: "🇹🇩", code: "+235", iso: "TD", name: "Chad" },
  { flag: "🇳🇪", code: "+227", iso: "NE", name: "Niger" },
  { flag: "🇲🇱", code: "+223", iso: "ML", name: "Mali" },
  { flag: "🇧🇫", code: "+226", iso: "BF", name: "Burkina Faso" },
  { flag: "🇬🇳", code: "+224", iso: "GN", name: "Guinea" },
  { flag: "🇸🇱", code: "+232", iso: "SL", name: "Sierra Leone" },
  { flag: "🇱🇷", code: "+231", iso: "LR", name: "Liberia" },
  { flag: "🇹🇬", code: "+228", iso: "TG", name: "Togo" },
  { flag: "🇧🇯", code: "+229", iso: "BJ", name: "Benin" },
  { flag: "🇲🇷", code: "+222", iso: "MR", name: "Mauritania" },
  { flag: "🇬🇲", code: "+220", iso: "GM", name: "Gambia" },
  { flag: "🇬🇼", code: "+245", iso: "GW", name: "Guinea-Bissau" },
  { flag: "🇨🇻", code: "+238", iso: "CV", name: "Cape Verde" },
  { flag: "🇸🇨", code: "+248", iso: "SC", name: "Seychelles" },
  { flag: "🇲🇺", code: "+230", iso: "MU", name: "Mauritius" },
  { flag: "🇲🇬", code: "+261", iso: "MG", name: "Madagascar" },
  { flag: "🇰🇲", code: "+269", iso: "KM", name: "Comoros" },
  { flag: "🇳🇦", code: "+264", iso: "NA", name: "Namibia" },
  { flag: "🇱🇸", code: "+266", iso: "LS", name: "Lesotho" },
  { flag: "🇸🇿", code: "+268", iso: "SZ", name: "Eswatini" },
  // Europe
  { flag: "🇬🇧", code: "+44",  iso: "GB", name: "United Kingdom" },
  { flag: "🇩🇪", code: "+49",  iso: "DE", name: "Germany" },
  { flag: "🇫🇷", code: "+33",  iso: "FR", name: "France" },
  { flag: "🇮🇹", code: "+39",  iso: "IT", name: "Italy" },
  { flag: "🇪🇸", code: "+34",  iso: "ES", name: "Spain" },
  { flag: "🇵🇹", code: "+351", iso: "PT", name: "Portugal" },
  { flag: "🇳🇱", code: "+31",  iso: "NL", name: "Netherlands" },
  { flag: "🇧🇪", code: "+32",  iso: "BE", name: "Belgium" },
  { flag: "🇨🇭", code: "+41",  iso: "CH", name: "Switzerland" },
  { flag: "🇦🇹", code: "+43",  iso: "AT", name: "Austria" },
  { flag: "🇸🇪", code: "+46",  iso: "SE", name: "Sweden" },
  { flag: "🇳🇴", code: "+47",  iso: "NO", name: "Norway" },
  { flag: "🇩🇰", code: "+45",  iso: "DK", name: "Denmark" },
  { flag: "🇫🇮", code: "+358", iso: "FI", name: "Finland" },
  { flag: "🇵🇱", code: "+48",  iso: "PL", name: "Poland" },
  { flag: "🇨🇿", code: "+420", iso: "CZ", name: "Czech Republic" },
  { flag: "🇷🇴", code: "+40",  iso: "RO", name: "Romania" },
  { flag: "🇭🇺", code: "+36",  iso: "HU", name: "Hungary" },
  { flag: "🇬🇷", code: "+30",  iso: "GR", name: "Greece" },
  { flag: "🇺🇦", code: "+380", iso: "UA", name: "Ukraine" },
  { flag: "🇷🇺", code: "+7",   iso: "RU", name: "Russia" },
  { flag: "🇹🇷", code: "+90",  iso: "TR", name: "Turkey" },
  // Americas
  { flag: "🇺🇸", code: "+1",   iso: "US", name: "United States" },
  { flag: "🇨🇦", code: "+1",   iso: "CA", name: "Canada" },
  { flag: "🇧🇷", code: "+55",  iso: "BR", name: "Brazil" },
  { flag: "🇲🇽", code: "+52",  iso: "MX", name: "Mexico" },
  { flag: "🇦🇷", code: "+54",  iso: "AR", name: "Argentina" },
  { flag: "🇨🇴", code: "+57",  iso: "CO", name: "Colombia" },
  { flag: "🇨🇱", code: "+56",  iso: "CL", name: "Chile" },
  { flag: "🇵🇪", code: "+51",  iso: "PE", name: "Peru" },
  { flag: "🇻🇪", code: "+58",  iso: "VE", name: "Venezuela" },
  { flag: "🇪🇨", code: "+593", iso: "EC", name: "Ecuador" },
  // Asia & Middle East
  { flag: "🇮🇳", code: "+91",  iso: "IN", name: "India" },
  { flag: "🇵🇰", code: "+92",  iso: "PK", name: "Pakistan" },
  { flag: "🇧🇩", code: "+880", iso: "BD", name: "Bangladesh" },
  { flag: "🇨🇳", code: "+86",  iso: "CN", name: "China" },
  { flag: "🇯🇵", code: "+81",  iso: "JP", name: "Japan" },
  { flag: "🇰🇷", code: "+82",  iso: "KR", name: "South Korea" },
  { flag: "🇮🇩", code: "+62",  iso: "ID", name: "Indonesia" },
  { flag: "🇵🇭", code: "+63",  iso: "PH", name: "Philippines" },
  { flag: "🇹🇭", code: "+66",  iso: "TH", name: "Thailand" },
  { flag: "🇻🇳", code: "+84",  iso: "VN", name: "Vietnam" },
  { flag: "🇲🇾", code: "+60",  iso: "MY", name: "Malaysia" },
  { flag: "🇸🇬", code: "+65",  iso: "SG", name: "Singapore" },
  { flag: "🇦🇪", code: "+971", iso: "AE", name: "UAE" },
  { flag: "🇸🇦", code: "+966", iso: "SA", name: "Saudi Arabia" },
  { flag: "🇮🇱", code: "+972", iso: "IL", name: "Israel" },
  { flag: "🇯🇴", code: "+962", iso: "JO", name: "Jordan" },
  { flag: "🇱🇧", code: "+961", iso: "LB", name: "Lebanon" },
  { flag: "🇮🇶", code: "+964", iso: "IQ", name: "Iraq" },
  { flag: "🇮🇷", code: "+98",  iso: "IR", name: "Iran" },
  { flag: "🇰🇼", code: "+965", iso: "KW", name: "Kuwait" },
  { flag: "🇶🇦", code: "+974", iso: "QA", name: "Qatar" },
  { flag: "🇧🇭", code: "+973", iso: "BH", name: "Bahrain" },
  { flag: "🇴🇲", code: "+968", iso: "OM", name: "Oman" },
  // Oceania
  { flag: "🇦🇺", code: "+61",  iso: "AU", name: "Australia" },
  { flag: "🇳🇿", code: "+64",  iso: "NZ", name: "New Zealand" },
];
