const SOCCER = (id: number) => `https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png`;
const NBA    = (id: number) => `https://a.espncdn.com/i/teamlogos/nba/500/${id}.png`;

export const TEAM_LOGOS: Record<string, string> = {
  // ── Premier League ────────────────────────────────────────────────────────
  "Arsenal":                    SOCCER(359),
  "Aston Villa":                SOCCER(362),
  "Bournemouth":                SOCCER(349),
  "Brentford":                  SOCCER(337),
  "Brighton":                   SOCCER(331),
  "Brighton and Hove Albion":   SOCCER(331),
  "Chelsea":                    SOCCER(363),
  "Crystal Palace":             SOCCER(384),
  "Everton":                    SOCCER(368),
  "Fulham":                     SOCCER(370),
  "Ipswich Town":               SOCCER(373),
  "Leicester City":             SOCCER(375),
  "Liverpool":                  SOCCER(364),
  "Manchester City":            SOCCER(382),
  "Manchester United":          SOCCER(360),
  "Newcastle United":           SOCCER(361),
  "Nottingham Forest":          SOCCER(393),
  "Southampton":                SOCCER(376),
  "Tottenham Hotspur":          SOCCER(367),
  "Tottenham":                  SOCCER(367),
  "West Ham United":            SOCCER(371),
  "West Ham":                   SOCCER(371),
  "Wolverhampton Wanderers":    SOCCER(380),
  "Wolves":                     SOCCER(380),
  "Sunderland":                 SOCCER(379),
  "Burnley":                    SOCCER(348),
  "Leeds United":               SOCCER(357),
  "Luton Town":                 SOCCER(389),
  "Sheffield United":           SOCCER(375),

  // ── La Liga ───────────────────────────────────────────────────────────────
  "Barcelona":                  SOCCER(83),
  "Real Madrid":                SOCCER(86),
  "Atletico Madrid":            SOCCER(1068),
  "Atlético Madrid":            SOCCER(1068),
  "Sevilla":                    SOCCER(243),
  "Real Betis":                 SOCCER(244),
  "Athletic Club":              SOCCER(93),
  "Athletic Bilbao":            SOCCER(93),
  "Valencia":                   SOCCER(95),
  "Villarreal":                 SOCCER(94),
  "Real Sociedad":              SOCCER(89),
  "Girona":                     SOCCER(9812),
  "Osasuna":                    SOCCER(88),
  "Celta Vigo":                 SOCCER(3842),
  "Getafe":                     SOCCER(3751),
  "Rayo Vallecano":             SOCCER(3750),
  "Alaves":                     SOCCER(3738),
  "Deportivo Alaves":           SOCCER(3738),
  "Alavés":                     SOCCER(3738),
  "Mallorca":                   SOCCER(9906),
  "Espanyol":                   SOCCER(3748),
  "Leganes":                    SOCCER(9813),
  "Leganés":                    SOCCER(9813),
  "Valladolid":                 SOCCER(9811),
  "Real Valladolid":            SOCCER(9811),
  "Las Palmas":                 SOCCER(9815),

  // ── Bundesliga ────────────────────────────────────────────────────────────
  "Bayern Munich":              SOCCER(132),
  "FC Bayern Munich":           SOCCER(132),
  "Borussia Dortmund":          SOCCER(124),
  "Bayer Leverkusen":           SOCCER(131),
  "RB Leipzig":                 SOCCER(23826),
  "Eintracht Frankfurt":        SOCCER(9823),
  "VfB Stuttgart":              SOCCER(128),
  "Stuttgart":                  SOCCER(128),
  "SC Freiburg":                SOCCER(9821),
  "Freiburg":                   SOCCER(9821),
  "TSG Hoffenheim":             SOCCER(9822),
  "Hoffenheim":                 SOCCER(9822),
  "Borussia Monchengladbach":   SOCCER(130),
  "Borussia Mönchengladbach":   SOCCER(130),
  "VfL Wolfsburg":              SOCCER(129),
  "Wolfsburg":                  SOCCER(129),
  "Werder Bremen":              SOCCER(9835),
  "FC Augsburg":                SOCCER(15985),
  "Augsburg":                   SOCCER(15985),
  "1. FSV Mainz 05":            SOCCER(16040),
  "Mainz":                      SOCCER(16040),
  "Mainz 05":                   SOCCER(16040),
  "Union Berlin":               SOCCER(43090),
  "1. FC Union Berlin":         SOCCER(43090),
  "FC Heidenheim":              SOCCER(43092),
  "Heidenheim":                 SOCCER(43092),
  "VfL Bochum":                 SOCCER(15984),
  "Bochum":                     SOCCER(15984),
  "Holstein Kiel":              SOCCER(16042),
  "FC St. Pauli":               SOCCER(16041),

  // ── Serie A ───────────────────────────────────────────────────────────────
  "Inter Milan":                SOCCER(110),
  "Internazionale":             SOCCER(110),
  "Inter":                      SOCCER(110),
  "AC Milan":                   SOCCER(103),
  "Milan":                      SOCCER(103),
  "Juventus":                   SOCCER(111),
  "Napoli":                     SOCCER(113),
  "AS Roma":                    SOCCER(104),
  "Roma":                       SOCCER(104),
  "Lazio":                      SOCCER(112),
  "SS Lazio":                   SOCCER(112),
  "Atalanta":                   SOCCER(108),
  "Fiorentina":                 SOCCER(109),
  "Bologna":                    SOCCER(107),
  "Torino":                     SOCCER(115),
  "Udinese":                    SOCCER(116),
  "Cagliari":                   SOCCER(14998),
  "Sassuolo":                   SOCCER(23809),
  "Empoli":                     SOCCER(14961),
  "Monza":                      SOCCER(43089),
  "Salernitana":                SOCCER(14999),
  "Venezia":                    SOCCER(14997),
  "Como":                       SOCCER(14996),
  "Lecce":                      SOCCER(23810),
  "Hellas Verona":              SOCCER(23811),
  "Verona":                     SOCCER(23811),
  "Genoa":                      SOCCER(14995),
  "Frosinone":                  SOCCER(23808),
  "Parma":                      SOCCER(14993),

  // ── NBA ───────────────────────────────────────────────────────────────────
  "Atlanta Hawks":              NBA(1),
  "Boston Celtics":             NBA(2),
  "Brooklyn Nets":              NBA(17),
  "Charlotte Hornets":          NBA(30),
  "Chicago Bulls":              NBA(4),
  "Cleveland Cavaliers":        NBA(5),
  "Dallas Mavericks":           NBA(6),
  "Denver Nuggets":             NBA(7),
  "Detroit Pistons":            NBA(8),
  "Golden State Warriors":      NBA(9),
  "Houston Rockets":            NBA(10),
  "Indiana Pacers":             NBA(11),
  "Los Angeles Clippers":       NBA(12),
  "LA Clippers":                NBA(12),
  "Los Angeles Lakers":         NBA(13),
  "LA Lakers":                  NBA(13),
  "Memphis Grizzlies":          NBA(29),
  "Miami Heat":                 NBA(14),
  "Milwaukee Bucks":            NBA(15),
  "Minnesota Timberwolves":     NBA(16),
  "New Orleans Pelicans":       NBA(3),
  "New York Knicks":            NBA(18),
  "Oklahoma City Thunder":      NBA(25),
  "Orlando Magic":              NBA(19),
  "Philadelphia 76ers":         NBA(20),
  "Phoenix Suns":               NBA(21),
  "Portland Trail Blazers":     NBA(22),
  "Sacramento Kings":           NBA(23),
  "San Antonio Spurs":          NBA(24),
  "Toronto Raptors":            NBA(28),
  "Utah Jazz":                  NBA(26),
  "Washington Wizards":         NBA(27),
  "New Orleans Hornets":        NBA(3),
};

export function getTeamLogo(name: string): string | undefined {
  return TEAM_LOGOS[name] ?? TEAM_LOGOS[name.trim()] ?? undefined;
}
