/**
 * World countries for the market picker (ISO 3166-1 alpha-2 + ISO 4217).
 * Payment rails resolve via currency in country-methods / method-registry.
 */
export type WorldCountry = {
  /** ISO 3166-1 alpha-2 — used for flagcdn */
  code: string;
  name: string;
  currency: string;
  currencyName: string;
};

export const WORLD_COUNTRIES: WorldCountry[] = [
  { code: "AF", name: "Afghanistan", currency: "AFN", currencyName: "Afghan Afghani" },
  { code: "AL", name: "Albania", currency: "ALL", currencyName: "Albanian Lek" },
  { code: "DZ", name: "Algeria", currency: "DZD", currencyName: "Algerian Dinar" },
  { code: "AD", name: "Andorra", currency: "EUR", currencyName: "Euro" },
  { code: "AO", name: "Angola", currency: "AOA", currencyName: "Angolan Kwanza" },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD", currencyName: "East Caribbean Dollar" },
  { code: "AR", name: "Argentina", currency: "ARS", currencyName: "Argentine Peso" },
  { code: "AM", name: "Armenia", currency: "AMD", currencyName: "Armenian Dram" },
  { code: "AU", name: "Australia", currency: "AUD", currencyName: "Australian Dollar" },
  { code: "AT", name: "Austria", currency: "EUR", currencyName: "Euro" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", currencyName: "Azerbaijani Manat" },
  { code: "BS", name: "Bahamas", currency: "BSD", currencyName: "Bahamian Dollar" },
  { code: "BH", name: "Bahrain", currency: "BHD", currencyName: "Bahraini Dinar" },
  { code: "BD", name: "Bangladesh", currency: "BDT", currencyName: "Bangladeshi Taka" },
  { code: "BB", name: "Barbados", currency: "BBD", currencyName: "Barbadian Dollar" },
  { code: "BY", name: "Belarus", currency: "BYN", currencyName: "Belarusian Ruble" },
  { code: "BE", name: "Belgium", currency: "EUR", currencyName: "Euro" },
  { code: "BZ", name: "Belize", currency: "BZD", currencyName: "Belize Dollar" },
  { code: "BJ", name: "Benin", currency: "XOF", currencyName: "West African CFA Franc" },
  { code: "BT", name: "Bhutan", currency: "BTN", currencyName: "Bhutanese Ngultrum" },
  { code: "BO", name: "Bolivia", currency: "BOB", currencyName: "Bolivian Boliviano" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", currencyName: "Convertible Mark" },
  { code: "BW", name: "Botswana", currency: "BWP", currencyName: "Botswana Pula" },
  { code: "BR", name: "Brazil", currency: "BRL", currencyName: "Brazilian Real" },
  { code: "BN", name: "Brunei", currency: "BND", currencyName: "Brunei Dollar" },
  { code: "BG", name: "Bulgaria", currency: "BGN", currencyName: "Bulgarian Lev" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", currencyName: "West African CFA Franc" },
  { code: "BI", name: "Burundi", currency: "BIF", currencyName: "Burundian Franc" },
  { code: "CV", name: "Cabo Verde", currency: "CVE", currencyName: "Cape Verdean Escudo" },
  { code: "KH", name: "Cambodia", currency: "KHR", currencyName: "Cambodian Riel" },
  { code: "CM", name: "Cameroon", currency: "XAF", currencyName: "Central African CFA Franc" },
  { code: "CA", name: "Canada", currency: "CAD", currencyName: "Canadian Dollar" },
  { code: "CF", name: "Central African Republic", currency: "XAF", currencyName: "Central African CFA Franc" },
  { code: "TD", name: "Chad", currency: "XAF", currencyName: "Central African CFA Franc" },
  { code: "CL", name: "Chile", currency: "CLP", currencyName: "Chilean Peso" },
  { code: "CN", name: "China", currency: "CNY", currencyName: "Chinese Yuan" },
  { code: "CO", name: "Colombia", currency: "COP", currencyName: "Colombian Peso" },
  { code: "KM", name: "Comoros", currency: "KMF", currencyName: "Comorian Franc" },
  { code: "CG", name: "Congo", currency: "XAF", currencyName: "Central African CFA Franc" },
  { code: "CD", name: "DR Congo", currency: "CDF", currencyName: "Congolese Franc" },
  { code: "CR", name: "Costa Rica", currency: "CRC", currencyName: "Costa Rican Colón" },
  { code: "CI", name: "Côte d'Ivoire", currency: "XOF", currencyName: "West African CFA Franc" },
  { code: "HR", name: "Croatia", currency: "EUR", currencyName: "Euro" },
  { code: "CU", name: "Cuba", currency: "CUP", currencyName: "Cuban Peso" },
  { code: "CY", name: "Cyprus", currency: "EUR", currencyName: "Euro" },
  { code: "CZ", name: "Czechia", currency: "CZK", currencyName: "Czech Koruna" },
  { code: "DK", name: "Denmark", currency: "DKK", currencyName: "Danish Krone" },
  { code: "DJ", name: "Djibouti", currency: "DJF", currencyName: "Djiboutian Franc" },
  { code: "DM", name: "Dominica", currency: "XCD", currencyName: "East Caribbean Dollar" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", currencyName: "Dominican Peso" },
  { code: "EC", name: "Ecuador", currency: "USD", currencyName: "US Dollar" },
  { code: "EG", name: "Egypt", currency: "EGP", currencyName: "Egyptian Pound" },
  { code: "SV", name: "El Salvador", currency: "USD", currencyName: "US Dollar" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", currencyName: "Central African CFA Franc" },
  { code: "ER", name: "Eritrea", currency: "ERN", currencyName: "Eritrean Nakfa" },
  { code: "EE", name: "Estonia", currency: "EUR", currencyName: "Euro" },
  { code: "SZ", name: "Eswatini", currency: "SZL", currencyName: "Lilangeni" },
  { code: "ET", name: "Ethiopia", currency: "ETB", currencyName: "Ethiopian Birr" },
  { code: "FJ", name: "Fiji", currency: "FJD", currencyName: "Fijian Dollar" },
  { code: "FI", name: "Finland", currency: "EUR", currencyName: "Euro" },
  { code: "FR", name: "France", currency: "EUR", currencyName: "Euro" },
  { code: "GA", name: "Gabon", currency: "XAF", currencyName: "Central African CFA Franc" },
  { code: "GM", name: "Gambia", currency: "GMD", currencyName: "Gambian Dalasi" },
  { code: "GE", name: "Georgia", currency: "GEL", currencyName: "Georgian Lari" },
  { code: "DE", name: "Germany", currency: "EUR", currencyName: "Euro" },
  { code: "GH", name: "Ghana", currency: "GHS", currencyName: "Ghanaian Cedi" },
  { code: "GR", name: "Greece", currency: "EUR", currencyName: "Euro" },
  { code: "GD", name: "Grenada", currency: "XCD", currencyName: "East Caribbean Dollar" },
  { code: "GT", name: "Guatemala", currency: "GTQ", currencyName: "Guatemalan Quetzal" },
  { code: "GN", name: "Guinea", currency: "GNF", currencyName: "Guinean Franc" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", currencyName: "West African CFA Franc" },
  { code: "GY", name: "Guyana", currency: "GYD", currencyName: "Guyanese Dollar" },
  { code: "HT", name: "Haiti", currency: "HTG", currencyName: "Haitian Gourde" },
  { code: "HN", name: "Honduras", currency: "HNL", currencyName: "Honduran Lempira" },
  { code: "HK", name: "Hong Kong", currency: "HKD", currencyName: "Hong Kong Dollar" },
  { code: "HU", name: "Hungary", currency: "HUF", currencyName: "Hungarian Forint" },
  { code: "IS", name: "Iceland", currency: "ISK", currencyName: "Icelandic Króna" },
  { code: "IN", name: "India", currency: "INR", currencyName: "Indian Rupee" },
  { code: "ID", name: "Indonesia", currency: "IDR", currencyName: "Indonesian Rupiah" },
  { code: "IR", name: "Iran", currency: "IRR", currencyName: "Iranian Rial" },
  { code: "IQ", name: "Iraq", currency: "IQD", currencyName: "Iraqi Dinar" },
  { code: "IE", name: "Ireland", currency: "EUR", currencyName: "Euro" },
  { code: "IL", name: "Israel", currency: "ILS", currencyName: "Israeli Shekel" },
  { code: "IT", name: "Italy", currency: "EUR", currencyName: "Euro" },
  { code: "JM", name: "Jamaica", currency: "JMD", currencyName: "Jamaican Dollar" },
  { code: "JP", name: "Japan", currency: "JPY", currencyName: "Japanese Yen" },
  { code: "JO", name: "Jordan", currency: "JOD", currencyName: "Jordanian Dinar" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", currencyName: "Kazakhstani Tenge" },
  { code: "KE", name: "Kenya", currency: "KES", currencyName: "Kenyan Shilling" },
  { code: "KI", name: "Kiribati", currency: "AUD", currencyName: "Australian Dollar" },
  { code: "KW", name: "Kuwait", currency: "KWD", currencyName: "Kuwaiti Dinar" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", currencyName: "Kyrgyzstani Som" },
  { code: "LA", name: "Laos", currency: "LAK", currencyName: "Lao Kip" },
  { code: "LV", name: "Latvia", currency: "EUR", currencyName: "Euro" },
  { code: "LB", name: "Lebanon", currency: "LBP", currencyName: "Lebanese Pound" },
  { code: "LS", name: "Lesotho", currency: "LSL", currencyName: "Lesotho Loti" },
  { code: "LR", name: "Liberia", currency: "LRD", currencyName: "Liberian Dollar" },
  { code: "LY", name: "Libya", currency: "LYD", currencyName: "Libyan Dinar" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", currencyName: "Swiss Franc" },
  { code: "LT", name: "Lithuania", currency: "EUR", currencyName: "Euro" },
  { code: "LU", name: "Luxembourg", currency: "EUR", currencyName: "Euro" },
  { code: "MG", name: "Madagascar", currency: "MGA", currencyName: "Malagasy Ariary" },
  { code: "MW", name: "Malawi", currency: "MWK", currencyName: "Malawian Kwacha" },
  { code: "MY", name: "Malaysia", currency: "MYR", currencyName: "Malaysian Ringgit" },
  { code: "MV", name: "Maldives", currency: "MVR", currencyName: "Maldivian Rufiyaa" },
  { code: "ML", name: "Mali", currency: "XOF", currencyName: "West African CFA Franc" },
  { code: "MT", name: "Malta", currency: "EUR", currencyName: "Euro" },
  { code: "MH", name: "Marshall Islands", currency: "USD", currencyName: "US Dollar" },
  { code: "MR", name: "Mauritania", currency: "MRU", currencyName: "Mauritanian Ouguiya" },
  { code: "MU", name: "Mauritius", currency: "MUR", currencyName: "Mauritian Rupee" },
  { code: "MX", name: "Mexico", currency: "MXN", currencyName: "Mexican Peso" },
  { code: "FM", name: "Micronesia", currency: "USD", currencyName: "US Dollar" },
  { code: "MD", name: "Moldova", currency: "MDL", currencyName: "Moldovan Leu" },
  { code: "MC", name: "Monaco", currency: "EUR", currencyName: "Euro" },
  { code: "MN", name: "Mongolia", currency: "MNT", currencyName: "Mongolian Tögrög" },
  { code: "ME", name: "Montenegro", currency: "EUR", currencyName: "Euro" },
  { code: "MA", name: "Morocco", currency: "MAD", currencyName: "Moroccan Dirham" },
  { code: "MZ", name: "Mozambique", currency: "MZN", currencyName: "Mozambican Metical" },
  { code: "MM", name: "Myanmar", currency: "MMK", currencyName: "Myanmar Kyat" },
  { code: "NA", name: "Namibia", currency: "NAD", currencyName: "Namibian Dollar" },
  { code: "NR", name: "Nauru", currency: "AUD", currencyName: "Australian Dollar" },
  { code: "NP", name: "Nepal", currency: "NPR", currencyName: "Nepalese Rupee" },
  { code: "NL", name: "Netherlands", currency: "EUR", currencyName: "Euro" },
  { code: "NZ", name: "New Zealand", currency: "NZD", currencyName: "New Zealand Dollar" },
  { code: "NI", name: "Nicaragua", currency: "NIO", currencyName: "Nicaraguan Córdoba" },
  { code: "NE", name: "Niger", currency: "XOF", currencyName: "West African CFA Franc" },
  { code: "NG", name: "Nigeria", currency: "NGN", currencyName: "Nigerian Naira" },
  { code: "KP", name: "North Korea", currency: "KPW", currencyName: "North Korean Won" },
  { code: "MK", name: "North Macedonia", currency: "MKD", currencyName: "Macedonian Denar" },
  { code: "NO", name: "Norway", currency: "NOK", currencyName: "Norwegian Krone" },
  { code: "OM", name: "Oman", currency: "OMR", currencyName: "Omani Rial" },
  { code: "PK", name: "Pakistan", currency: "PKR", currencyName: "Pakistani Rupee" },
  { code: "PW", name: "Palau", currency: "USD", currencyName: "US Dollar" },
  { code: "PS", name: "Palestine", currency: "ILS", currencyName: "Israeli Shekel" },
  { code: "PA", name: "Panama", currency: "PAB", currencyName: "Panamanian Balboa" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", currencyName: "Papua New Guinean Kina" },
  { code: "PY", name: "Paraguay", currency: "PYG", currencyName: "Paraguayan Guaraní" },
  { code: "PE", name: "Peru", currency: "PEN", currencyName: "Peruvian Sol" },
  { code: "PH", name: "Philippines", currency: "PHP", currencyName: "Philippine Peso" },
  { code: "PL", name: "Poland", currency: "PLN", currencyName: "Polish Złoty" },
  { code: "PT", name: "Portugal", currency: "EUR", currencyName: "Euro" },
  { code: "QA", name: "Qatar", currency: "QAR", currencyName: "Qatari Riyal" },
  { code: "RO", name: "Romania", currency: "RON", currencyName: "Romanian Leu" },
  { code: "RU", name: "Russia", currency: "RUB", currencyName: "Russian Ruble" },
  { code: "RW", name: "Rwanda", currency: "RWF", currencyName: "Rwandan Franc" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", currencyName: "East Caribbean Dollar" },
  { code: "LC", name: "Saint Lucia", currency: "XCD", currencyName: "East Caribbean Dollar" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency: "XCD", currencyName: "East Caribbean Dollar" },
  { code: "WS", name: "Samoa", currency: "WST", currencyName: "Samoan Tala" },
  { code: "SM", name: "San Marino", currency: "EUR", currencyName: "Euro" },
  { code: "ST", name: "São Tomé and Príncipe", currency: "STN", currencyName: "São Tomé Dobra" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", currencyName: "Saudi Riyal" },
  { code: "SN", name: "Senegal", currency: "XOF", currencyName: "West African CFA Franc" },
  { code: "RS", name: "Serbia", currency: "RSD", currencyName: "Serbian Dinar" },
  { code: "SC", name: "Seychelles", currency: "SCR", currencyName: "Seychellois Rupee" },
  { code: "SL", name: "Sierra Leone", currency: "SLE", currencyName: "Sierra Leonean Leone" },
  { code: "SG", name: "Singapore", currency: "SGD", currencyName: "Singapore Dollar" },
  { code: "SK", name: "Slovakia", currency: "EUR", currencyName: "Euro" },
  { code: "SI", name: "Slovenia", currency: "EUR", currencyName: "Euro" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", currencyName: "Solomon Islands Dollar" },
  { code: "SO", name: "Somalia", currency: "SOS", currencyName: "Somali Shilling" },
  { code: "ZA", name: "South Africa", currency: "ZAR", currencyName: "South African Rand" },
  { code: "KR", name: "South Korea", currency: "KRW", currencyName: "South Korean Won" },
  { code: "SS", name: "South Sudan", currency: "SSP", currencyName: "South Sudanese Pound" },
  { code: "ES", name: "Spain", currency: "EUR", currencyName: "Euro" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", currencyName: "Sri Lankan Rupee" },
  { code: "SD", name: "Sudan", currency: "SDG", currencyName: "Sudanese Pound" },
  { code: "SR", name: "Suriname", currency: "SRD", currencyName: "Surinamese Dollar" },
  { code: "SE", name: "Sweden", currency: "SEK", currencyName: "Swedish Krona" },
  { code: "CH", name: "Switzerland", currency: "CHF", currencyName: "Swiss Franc" },
  { code: "SY", name: "Syria", currency: "SYP", currencyName: "Syrian Pound" },
  { code: "TW", name: "Taiwan", currency: "TWD", currencyName: "New Taiwan Dollar" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", currencyName: "Tajikistani Somoni" },
  { code: "TZ", name: "Tanzania", currency: "TZS", currencyName: "Tanzanian Shilling" },
  { code: "TH", name: "Thailand", currency: "THB", currencyName: "Thai Baht" },
  { code: "TL", name: "Timor-Leste", currency: "USD", currencyName: "US Dollar" },
  { code: "TG", name: "Togo", currency: "XOF", currencyName: "West African CFA Franc" },
  { code: "TO", name: "Tonga", currency: "TOP", currencyName: "Tongan Paʻanga" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", currencyName: "Trinidad and Tobago Dollar" },
  { code: "TN", name: "Tunisia", currency: "TND", currencyName: "Tunisian Dinar" },
  { code: "TR", name: "Türkiye", currency: "TRY", currencyName: "Turkish Lira" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", currencyName: "Turkmenistani Manat" },
  { code: "TV", name: "Tuvalu", currency: "AUD", currencyName: "Australian Dollar" },
  { code: "UG", name: "Uganda", currency: "UGX", currencyName: "Ugandan Shilling" },
  { code: "UA", name: "Ukraine", currency: "UAH", currencyName: "Ukrainian Hryvnia" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", currencyName: "UAE Dirham" },
  { code: "GB", name: "United Kingdom", currency: "GBP", currencyName: "British Pound" },
  { code: "US", name: "United States", currency: "USD", currencyName: "US Dollar" },
  { code: "UY", name: "Uruguay", currency: "UYU", currencyName: "Uruguayan Peso" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", currencyName: "Uzbekistani Som" },
  { code: "VU", name: "Vanuatu", currency: "VUV", currencyName: "Vanuatu Vatu" },
  { code: "VA", name: "Vatican City", currency: "EUR", currencyName: "Euro" },
  { code: "VE", name: "Venezuela", currency: "VES", currencyName: "Venezuelan Bolívar" },
  { code: "VN", name: "Vietnam", currency: "VND", currencyName: "Vietnamese Dong" },
  { code: "YE", name: "Yemen", currency: "YER", currencyName: "Yemeni Rial" },
  { code: "ZM", name: "Zambia", currency: "ZMW", currencyName: "Zambian Kwacha" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", currencyName: "Zimbabwean Dollar" },
];

export const WORLD_BY_CODE: Record<string, WorldCountry> = Object.fromEntries(
  WORLD_COUNTRIES.map((c) => [c.code, c]),
);

export function countryFlagUrl(countryCode: string): string {
  return `https://flagcdn.com/w40/${countryCode.toLowerCase()}.png`;
}

export function findCountryByCurrency(currency: string): WorldCountry | undefined {
  return WORLD_COUNTRIES.find((c) => c.currency === currency);
}

/**
 * Detect visitor country from CDN/edge geo headers (Cloudflare / Vercel),
 * then accept-language region. Returns ISO 3166-1 alpha-2 or null.
 */
export function detectCountryFromHeaders(
  getHeader: (name: string) => string | null | undefined,
): string | null {
  const geoHeaders = [
    "cf-ipcountry",
    "x-vercel-ip-country",
    "x-country-code",
    "x-geo-country",
    "x-country",
  ];
  for (const h of geoHeaders) {
    const code = (getHeader(h) ?? "").trim().toUpperCase();
    if (!code || code === "XX" || code === "T1") continue;
    if (WORLD_BY_CODE[code]) return code;
  }
  const lang = getHeader("accept-language") ?? "";
  const m = /-([A-Za-z]{2})\b/.exec(lang);
  if (m) {
    const code = m[1].toUpperCase();
    if (WORLD_BY_CODE[code]) return code;
  }
  return null;
}
